### ISSUE TITLE
5ET-470 Slight UX change to make the makebrew hamburger more obvious visible

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#584]
**Feature Request**: Slight UX change to make the makebrew hamburger more obvious visible

**Extra Information **
**Who would use it?** new homebrewers
**How would it work?** css stylesheet change
```css
.sidemenu__toggle {
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
    background: lightgrey;
    position: absolute;
    z-index: 60;
    top: 46px;
    left: -1px;
    width: 32px;
    height: 32px;
    cursor: pointer;
    transition: left 51ms;
    display: flex;
    flex-direction: column;
    justify-content: space-around;
    padding: 3px 4px;
}

.night-mode .sidemenu__toggle {
    background: lightblue;
}
```
(something that creates or highlights its existence, like having the sidemenu open on load, but immediate close to give a visual indicator of its existence.)
**Why should this be added?**  contrast to bring attention to the feature tab. (People keep not seeing it) - maybe move it to the right side as well

- deleted_user_0ce0eb93436c

> Upvote - sigilblue (SigilBlue)

> Upvote - deraviin (deraviin)

> Upvote - 155435500159631360

> Upvote - lksaar (lksaar)

> Upvote - ikaguia (Ikaguia)

> Upvote - lxran (Lxran)

> Upvote - surged20 (Surge)

> Upvote - insaiyan7 (Insaiyan7)

> Upvote - deleted_user_0ce0eb93436c

> Upvote - arita (Arita)

> Upvote - umustalldie2 (Umustalldie2)

> Upvote - sgt_wolf (Marc)

> Upvote - plutohimself (Pluto Anatole)

> Upvote - warnickel (WarNickel)

> Upvote - .gor. (GoR)

> Upvote - 522909673859579975

> Upvote - spap (Spappz)

> Upvote - f0rgetful (absentminded)

> Upvote - kachow_45 (Kachow)

> Upvote - risky_biscuits (risky_biscuits)

> Upvote - revilowaldow (Lyra)

> Upvote - aceazzermeen (Ace)

> Upvote - amethysttheotter (amethyst the otter)

> Upvote - violkai (Violkai)

Votes: +24 / -0 / ±0
